/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	aadmicrosoftcomv1 "pkg/aadsync/apis/aad.microsoft.com/v1"
)

// FakeAADGroupSyncs implements AADGroupSyncInterface
type FakeAADGroupSyncs struct {
	Fake *FakeAadV1
	ns   string
}

var aadgroupsyncsResource = schema.GroupVersionResource{Group: "aad.microsoft.com", Version: "v1", Resource: "aadgroupsyncs"}

var aadgroupsyncsKind = schema.GroupVersionKind{Group: "aad.microsoft.com", Version: "v1", Kind: "AADGroupSync"}

// Get takes name of the aADGroupSync, and returns the corresponding aADGroupSync object, and an error if there is any.
func (c *FakeAADGroupSyncs) Get(name string, options v1.GetOptions) (result *aadmicrosoftcomv1.AADGroupSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aadgroupsyncsResource, c.ns, name), &aadmicrosoftcomv1.AADGroupSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aadmicrosoftcomv1.AADGroupSync), err
}

// List takes label and field selectors, and returns the list of AADGroupSyncs that match those selectors.
func (c *FakeAADGroupSyncs) List(opts v1.ListOptions) (result *aadmicrosoftcomv1.AADGroupSyncList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aadgroupsyncsResource, aadgroupsyncsKind, c.ns, opts), &aadmicrosoftcomv1.AADGroupSyncList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &aadmicrosoftcomv1.AADGroupSyncList{ListMeta: obj.(*aadmicrosoftcomv1.AADGroupSyncList).ListMeta}
	for _, item := range obj.(*aadmicrosoftcomv1.AADGroupSyncList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aADGroupSyncs.
func (c *FakeAADGroupSyncs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aadgroupsyncsResource, c.ns, opts))

}

// Create takes the representation of a aADGroupSync and creates it.  Returns the server's representation of the aADGroupSync, and an error, if there is any.
func (c *FakeAADGroupSyncs) Create(aADGroupSync *aadmicrosoftcomv1.AADGroupSync) (result *aadmicrosoftcomv1.AADGroupSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aadgroupsyncsResource, c.ns, aADGroupSync), &aadmicrosoftcomv1.AADGroupSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aadmicrosoftcomv1.AADGroupSync), err
}

// Update takes the representation of a aADGroupSync and updates it. Returns the server's representation of the aADGroupSync, and an error, if there is any.
func (c *FakeAADGroupSyncs) Update(aADGroupSync *aadmicrosoftcomv1.AADGroupSync) (result *aadmicrosoftcomv1.AADGroupSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aadgroupsyncsResource, c.ns, aADGroupSync), &aadmicrosoftcomv1.AADGroupSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aadmicrosoftcomv1.AADGroupSync), err
}

// Delete takes name of the aADGroupSync and deletes it. Returns an error if one occurs.
func (c *FakeAADGroupSyncs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(aadgroupsyncsResource, c.ns, name), &aadmicrosoftcomv1.AADGroupSync{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAADGroupSyncs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aadgroupsyncsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &aadmicrosoftcomv1.AADGroupSyncList{})
	return err
}

// Patch applies the patch and returns the patched aADGroupSync.
func (c *FakeAADGroupSyncs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *aadmicrosoftcomv1.AADGroupSync, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aadgroupsyncsResource, c.ns, name, pt, data, subresources...), &aadmicrosoftcomv1.AADGroupSync{})

	if obj == nil {
		return nil, err
	}
	return obj.(*aadmicrosoftcomv1.AADGroupSync), err
}
