/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "pkg/aadsync/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "pkg/aadsync/apis/aad.microsoft.com/v1"
)

// AADGroupSyncsGetter has a method to return a AADGroupSyncInterface.
// A group's client should implement this interface.
type AADGroupSyncsGetter interface {
	AADGroupSyncs(namespace string) AADGroupSyncInterface
}

// AADGroupSyncInterface has methods to work with AADGroupSync resources.
type AADGroupSyncInterface interface {
	Create(*v1.AADGroupSync) (*v1.AADGroupSync, error)
	Update(*v1.AADGroupSync) (*v1.AADGroupSync, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AADGroupSync, error)
	List(opts metav1.ListOptions) (*v1.AADGroupSyncList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AADGroupSync, err error)
	AADGroupSyncExpansion
}

// aADGroupSyncs implements AADGroupSyncInterface
type aADGroupSyncs struct {
	client rest.Interface
	ns     string
}

// newAADGroupSyncs returns a AADGroupSyncs
func newAADGroupSyncs(c *AadV1Client, namespace string) *aADGroupSyncs {
	return &aADGroupSyncs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aADGroupSync, and returns the corresponding aADGroupSync object, and an error if there is any.
func (c *aADGroupSyncs) Get(name string, options metav1.GetOptions) (result *v1.AADGroupSync, err error) {
	result = &v1.AADGroupSync{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AADGroupSyncs that match those selectors.
func (c *aADGroupSyncs) List(opts metav1.ListOptions) (result *v1.AADGroupSyncList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AADGroupSyncList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aADGroupSyncs.
func (c *aADGroupSyncs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a aADGroupSync and creates it.  Returns the server's representation of the aADGroupSync, and an error, if there is any.
func (c *aADGroupSyncs) Create(aADGroupSync *v1.AADGroupSync) (result *v1.AADGroupSync, err error) {
	result = &v1.AADGroupSync{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		Body(aADGroupSync).
		Do().
		Into(result)
	return
}

// Update takes the representation of a aADGroupSync and updates it. Returns the server's representation of the aADGroupSync, and an error, if there is any.
func (c *aADGroupSyncs) Update(aADGroupSync *v1.AADGroupSync) (result *v1.AADGroupSync, err error) {
	result = &v1.AADGroupSync{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		Name(aADGroupSync.Name).
		Body(aADGroupSync).
		Do().
		Into(result)
	return
}

// Delete takes name of the aADGroupSync and deletes it. Returns an error if one occurs.
func (c *aADGroupSyncs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aADGroupSyncs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched aADGroupSync.
func (c *aADGroupSyncs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AADGroupSync, err error) {
	result = &v1.AADGroupSync{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("aadgroupsyncs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
